version: "3"

services:
    nginx:
        image: nginx:1.23.0-alpine
        ports:
            - "80:80"
        container_name: "nginx"
        volumes:
            - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../public:/app/public

    php:
        build: ./configs/php
        container_name: "php"
        image: androidnetua/php:7-fpm-pdo-mysql-redis
        volumes:
            - ../:/app
#            - vendor:/app/vendor

    db:
        image: mariadb:10.8
        container_name: "db"
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MYSQL_DATABASE=over3
        volumes:
            - db_data:/var/lib/mysql

    pma:
        image: phpmyadmin:5.2.0-apache
        container_name: "pma"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MARIADB_ROOT_PASSWORD=root
        ports:
            - "8080:80"

    redis:
        image: redis:7.0
        container_name: redis
    redis-admin:
        image: erikdubbelboer/phpredisadmin
        container_name: redis-admin
        environment:
            - REDIS_1_HOST=redis
        ports:
            - "8081:80"


volumes:
    db_data:
#    vendor:
